### ISSUE TITLE
Missing fastentrypoints with Python 3.10.6

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#1048]
My build with master is broken. It seems that this commit is causing problems, although I'm not using Python 3.7 142289d71cc52309defb70ac7e8a50ba9fe1d243

Removing the Python 3.7 restriction makes my build pass: https://github.com/labgrid-project/labgrid/blob/2516e15dda5b0aba4b77d2dfd98a5d87707fad4b/pyproject.toml#L7

```
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-yyal2kb1/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-yyal2kb1/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-yyal2kb1/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'fastentrypoints'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by kjeldflarup** [comment]
Ups, found the bug. My Dockerfile did not clean and old /opt/labgrid from a parent container.
