### ISSUE TITLE
Coordinator: Failed to import class 'labgrid.remote.authenticator.AuthenticatorSession

### ISSUE THREAD

**Issue by ElenaGrigore** [labgrid-project/labgrid#1218]
After switching to latest labgrid code , crossbar fails to start with: Failed to import class labgrid.remote.authenticator.AuthenticatorSession error .

I have also tried to apply patch: https://github.com/labgrid-project/labgrid/pull/1216/commits but I get the same error. See attached the entire error and below just a snapshot:
```
2023-06-23T14:06:45+0200 [Router      22002] component loading failed
Traceback (most recent call last):
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/autobahn/wamp/websocket.py", line 103, in onMessage
    self._session.onMessage(msg)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/autobahn/wamp/protocol.py", line 1066, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/txaio/tx.py", line 369, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred
    result = f(*args, **kwargs)
--- <exception caught here> ---
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/router.py", line 712, in start_router_component
    create_component = _appsession_loader(config)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/__init__.py", line 78, in _appsession_loader
    raise ApplicationError(
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.class_import_failed>, args=['Failed to import class \'labgrid.remote.authenticator.AuthenticatorSession\'\nTraceback (most recent call last):\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/autobahn/wamp/protocol.py", line 1066, in onMessage\n    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/txaio/tx.py", line 369, in as_future\n    return maybeDeferred(fun, *args, **kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred\n    result = f(*args, **kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/router.py", line 712, in start_router_component\n    create_component = _appsession_loader(config)\n--- <exception caught here> ---\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/__init__.py", line 65, in _appsession_loader\n    module = importlib.import_module(module_name)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/importlib/__init__.py", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n    \n  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "/labgrid-tests/labgrid/labgrid/__init__.py", line 1, in <module>\n    from .target import Target\n  File "/labgrid-tests/labgrid/labgrid/target.py", line 10, in <module>\n    from .driver import Driver\n  File "/labgrid-tests/labgrid/labgrid/driver/__init__.py", line 1, in <module>\n    from .bareboxdriver import BareboxDriver\n  File "/labgrid-tests/labgrid/labgrid/driver/bareboxdriver.py", line 5, in <module>\n    from pexpect import TIMEOUT\nbuiltins.ModuleNotFoundError: No module named \'pexpect\'\n'], kwargs={'pythonpath': ['/labgrid-tests/labgrid', '/labgrid-tests/labgrid/crossbar-venv/bin', '/labgrid-tests/labgrid/crossbar-venv/lib/python38.zip', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages']}, enc_algo=None, callee=None, callee_authid=None, callee_authrole=None, forward_for=None)

2023-06-23T14:06:45+0200 [Router      22002]   Python module search paths:
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid/crossbar-venv/bin
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid/crossbar-venv/lib/python38.zip
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid/crossbar-venv/lib/python3.8
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid/crossbar-venv/lib/python3.8/lib-dynload
2023-06-23T14:06:45+0200 [Router      22002]     /usr/local/lib/python3.8
2023-06-23T14:06:45+0200 [Router      22002]     /labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages
2023-06-23T14:06:45+0200 [Controller  21993] Could not start node: Traceback (most recent call last):
--- <exception caught here> ---
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/node/node.py", line 468, in start
    res = yield self.personality.Node.boot(self)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/node/node.py", line 608, in boot_from_config
    yield d
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/node/node.py", line 581, in configure_worker
    yield config_fn(worker_logname, worker_id, worker)
  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/node/node.py", line 702, in _configure_native_worker_router
    yield self._controller.call('crossbar.worker.{}.start_router_component'.format(worker_id), component_id, component, options=CallOptions())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.class_import_failed>, args=['Failed to import class \'labgrid.remote.authenticator.AuthenticatorSession\'\nTraceback (most recent call last):\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/autobahn/wamp/protocol.py", line 1066, in onMessage\n    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/txaio/tx.py", line 369, in as_future\n    return maybeDeferred(fun, *args, **kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred\n    result = f(*args, **kwargs)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/router.py", line 712, in start_router_component\n    create_component = _appsession_loader(config)\n--- <exception caught here> ---\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages/crossbar/worker/__init__.py", line 65, in _appsession_loader\n    module = importlib.import_module(module_name)\n  File "/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/importlib/__init__.py", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 991, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\n    \n  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\n    \n  File "<frozen importlib._bootstrap_external>", line 783, in exec_module\n    \n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n    \n  File "/labgrid-tests/labgrid/labgrid/__init__.py", line 1, in <module>\n    from .target import Target\n  File "/labgrid-tests/labgrid/labgrid/target.py", line 10, in <module>\n    from .driver import Driver\n  File "/labgrid-tests/labgrid/labgrid/driver/__init__.py", line 1, in <module>\n    from .bareboxdriver import BareboxDriver\n  File "/labgrid-tests/labgrid/labgrid/driver/bareboxdriver.py", line 5, in <module>\n    from pexpect import TIMEOUT\nbuiltins.ModuleNotFoundError: No module named \'pexpect\'\n'], kwargs={'pythonpath': ['/labgrid-tests/labgrid', '/labgrid-tests/labgrid/crossbar-venv/bin', '/labgrid-tests/labgrid/crossbar-venv/lib/python38.zip', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8', '/labgrid-tests/labgrid/crossbar-venv/lib/python3.8/site-packages']}, enc_algo=None, callee=None, callee_authid=None, callee_authrole=None, forward_for=None)

```
[crossbar-error.txt](https://github.com/labgrid-project/labgrid/files/11848296/crossbar-error.txt)

**Comment by ElenaGrigore** [comment]
we used an outdated config file
