### ISSUE TITLE
SerialDriver: BindingErrors hidden by AttributeError caused by not (yet) set target

### ISSUE THREAD

**Issue by Bastian-Krause** [labgrid-project/labgrid#1414]
When creating an env config with wrong bindings, a completely unrelated error happens:
```python
$ labgrid-client con                                                                            
Selected role main from configuration file
Traceback (most recent call last):
  File "labgrid/labgrid/remote/client.py", line 1934, in main
    target = session._get_target(place)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/remote/client.py", line 671, in _get_target
    target = self.env.get_target(self.role)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/environment.py", line 49, in get_target
    target = target_factory.make_target(role, config, env=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/factory.py", line 159, in make_target
    self.make_driver(target, driver, name, args)
  File "labgrid/labgrid/factory.py", line 138, in make_driver
    d = cls(target, name, **args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init labgrid.driver.serialdriver.SerialDriver>", line 11, in __init__
    self.__attrs_post_init__()
  File "labgrid/labgrid/driver/serialdriver.py", line 26, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/driver/consoleexpectmixin.py", line 18, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/driver/common.py", line 25, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/binding.py", line 55, in __attrs_post_init__
    target.bind(self)
  File "labgrid/labgrid/target.py", line 430, in bind
    return self.bind_driver(bindable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/target.py", line 406, in bind_driver
    f"{client} got unexpected bindings: {list(mapping.keys())}"
      ^^^^^^^^
  File "labgrid/labgrid/driver/serialdriver.py", line 116, in __str__
    return f"SerialDriver({self.target.name})"
                           ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

When dropping SerialDriver's `__str___()` the actual error cause is shown:

```python
$ labgrid-client con
Selected role main from configuration file
Traceback (most recent call last):
  File "labgrid/labgrid/remote/client.py", line 1934, in main
    target = session._get_target(place)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/remote/client.py", line 671, in _get_target
    target = self.env.get_target(self.role)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/environment.py", line 49, in get_target
    target = target_factory.make_target(role, config, env=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/factory.py", line 159, in make_target
    self.make_driver(target, driver, name, args)
  File "labgrid/labgrid/factory.py", line 138, in make_driver
    d = cls(target, name, **args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init labgrid.driver.serialdriver.SerialDriver>", line 11, in __init__
    self.__attrs_post_init__()
  File "labgrid/labgrid/driver/serialdriver.py", line 26, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/driver/consoleexpectmixin.py", line 18, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/driver/common.py", line 25, in __attrs_post_init__
    super().__attrs_post_init__()
  File "labgrid/labgrid/binding.py", line 55, in __attrs_post_init__
    target.bind(self)
  File "labgrid/labgrid/target.py", line 430, in bind
    return self.bind_driver(bindable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "labgrid/labgrid/target.py", line 405, in bind_driver
    raise BindingError(
labgrid.binding.BindingError: SerialDriver() got unexpected bindings: ['serial']
```

This happens because the target checks if the driver (called client here) consumed all bindings before setting itself to `client.target`:

https://github.com/labgrid-project/labgrid/blob/9e0562e1c8d6842c850c239d64896b88c3bf3bd1/labgrid/target.py#L403-L418

 If that check fails, the driver's `__str__()` is called. In the case of the SerialDriver, `self.target.name` is used in this method.

I am not really sure what's the correct fix. Setting `client.target = self` earlier? I am unsure about the implications.

**Comment by Emantor** [comment]
IMO we should fix the `__str__` call sites as there are only two.

**Comment by Emantor** [comment]
@jluebbe Do you know why we unset the `target` in the `BindingMixin` in the first place and create this problem? Even if the target is not unset the state for the binding still indicates its current status in relation to the target and it won't break the assumption that the target is always set (which is used in the `__str__` implementations).

EDIT: Quick implementation in https://github.com/Emantor/labgrid/tree/fix/remove-driver-unset

**Comment by Emantor** [comment]
We looked at this:
- Resources can be created without a `Target`, this is done on the Exporter
- Drivers already expect the target to be set in all cases anyway (Driver baseclass asserts)
- A binding failure should be handled with more care to ensure a halfway constructed driver does not become visible via the target
