### ISSUE TITLE
(grpc) No module named 'labgrid.remote.generated'

### ISSUE THREAD

**Issue by sjg20** [labgrid-project/labgrid#1424]
I got this error trying the gitlab integration with grpc:

```
Traceback (most recent call last):
  File "/scratch/sglass/gitlab-runner/builds/maJ-y5z_5/0/u-boot/custodians/u-boot-dm/test/py/test.py", line [24](https://source.denx.de/u-boot/custodians/u-boot-dm/-/jobs/849713#L24), in <module>
    sys.exit(pytest.main(args))
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1060, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1348, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py", line 1231, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 1[26](https://source.denx.de/u-boot/custodians/u-boot-dm/-/jobs/849713#L26), in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 10[27](https://source.denx.de/u-boot/custodians/u-boot-dm/-/jobs/849713#L27), in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/scratch/sglass/gitlab-runner/.local/lib/python3.10/site-packages/labgrid/pytestplugin/__init__.py", line 1, in <module>
    from .fixtures import pytest_addoption, env, target, strategy
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/scratch/sglass/gitlab-runner/.local/lib/python3.10/site-packages/labgrid/pytestplugin/fixtures.py", line 6, in <module>
    from ..remote.client import UserError
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/scratch/sglass/gitlab-runner/.local/lib/python3.10/site-packages/labgrid/remote/client.py", line 27, in <module>
    import labgrid.remote.generated.labgrid_coordinator_pb2_grpc as labgrid_coordinator_pb2_grpc
ModuleNotFoundError: No module named 'labgrid.remote.generated'
$ U_BOOT_BOARD_IDENTITY="${ROLE}" u-boot-test-release || true
Traceback (most recent call last):
  File "/scratch/sglass/gitlab-runner/.local/bin/labgrid-client", line 5, in <module>
    from labgrid.remote.client import main
  File "/scratch/sglass/gitlab-runner/.local/lib/python3.10/site-packages/labgrid/remote/client.py", line 27, in <module>
    import labgrid.remote.generated.labgrid_coordinator_pb2_grpc as labgrid_coordinator_pb2_grpc
ModuleNotFoundError: No module named 'labgrid.remote.generated'
```

**Comment by sjg20** [comment]
With the latest grpc branch this seems to be fixed.
