### ISSUE TITLE
setuptools 72.0.0 breaks autobahn wheel build

### ISSUE THREAD

**Issue by Bastian-Krause** [labgrid-project/labgrid#1452]
```
Collecting autobahn>=21.3.1 (from labgrid==0.1.dev1)
  Using cached autobahn-23.6.2.tar.gz (480 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-vi_fte4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-vi_fte4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-vi_fte4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-vi_fte4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 32, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This error can be observed in our scheduled CI jobs: https://github.com/labgrid-project/labgrid/actions/runs/10140787667/job/28036680206
Jobs that use existing wheels do not fail.

Upstream autobahn issue: https://github.com/crossbario/autobahn-python/issues/1644

Upstream setuptools issue: https://github.com/pypa/setuptools/issues/4519

**Comment by Bastian-Krause** [comment]
[setuptools 72.0.0](https://pypi.org/project/setuptools/72.0.0/) has been yanked. [72.1.0](https://pypi.org/project/setuptools/72.1.0/) has been released with [the test command re-added and a louder deprecation](https://github.com/pypa/setuptools/pull/4522). Our CI works again.

I'm assuming that we've moved from autobahn to [gRPC](https://github.com/labgrid-project/labgrid/discussions/1417) once the test command is finally removed.
