### ISSUE TITLE
pytest internal error lg_feature

### ISSUE THREAD

**Issue by spark5** [labgrid-project/labgrid#372]
When running pytest, I am receiving this pytest internal error:

```
platform linux -- Python 3.5.2, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- labgrid-tests/venv/bin/python
cachedir: .pytest_cache
metadata: {'Platform': 'Linux-4.4.0-137-generic-x86_64-with-Ubuntu-16.04-xenial', 'Packages': {'py': '1.7.0', 'pytest': '4.1.0', 'pluggy': '0.8.0'}, 'Python': '3.5.2', 'Plugins': {'dependency': '0.4.0', 'metadata': '1.8.0', 'labgrid': '0.1.dev1097+gccaac07', 'html': '1.19.0'}}
rootdir: labgrid-tests, inifile:
plugins: labgrid-0.1.dev1097+gccaac07, metadata-1.8.0, html-1.19.0, dependency-0.4.0
collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/_pytest/main.py", line 468, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "labgrid-tests/venv/lib/python3.5/site-packages/labgrid-0.1.dev1097+gccaac07-py3.5.egg/labgrid/pytestplugin/hooks.py", line 57, in pytest_collection_modifyitems
INTERNALERROR>     marker = item.get_marker("lg_feature")
INTERNALERROR> AttributeError: 'Function' object has no attribute 'get_marker'
```

Do you happen to know the root cause of the problem?

**Comment by Emantor** [comment]
This should be fixed by https://github.com/labgrid-project/labgrid/commit/7227925fb3906e19ed9e706a7643e92e7c917900, please upgrade your labgrid installation.

**Comment by spark5** [comment]
Thanks!
